// Code generated by Slice Machine. DO NOT EDIT.

import ContactUs from './ContactUS';
import Hero from './Hero';
import IconText from './IconText';
import Image from './Image';
import ImageCards from './ImageCards';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';
import UserProfile from './UserProfile';

export {
	ContactUs,
	Hero,
	IconText,
	Image,
	ImageCards,
	Quote,
	Text,
	TextWithImage,
	UserProfile,
};

export const components = {
	contact_us: ContactUs,
	hero: Hero,
	icon_text: IconText,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
	user_profile: UserProfile,
};
