// Code generated by Slice Machine. DO NOT EDIT.

import CardCarousel from './CardCarousel';
import Clients from './Clients';
import ContactUs from './ContactUS';
import CustomerAction from './CustomerAction';
import Hero from './Hero';
import IconText from './IconText';
import Image from './Image';
import ImageCards from './ImageCards';
import Quote from './Quote';
import ServicesCarousel from './ServicesCarousel';
import Text from './Text';
import TextWithImage from './TextWithImage';
import UserProfile from './UserProfile';
import Video from './Video';

export {
	CardCarousel,
	Clients,
	ContactUs,
	CustomerAction,
	Hero,
	IconText,
	Image,
	ImageCards,
	Quote,
	ServicesCarousel,
	Text,
	TextWithImage,
	UserProfile,
	Video,
};

export const components = {
	card_carousel: CardCarousel,
	clients: Clients,
	contact_us: ContactUs,
	customer_action: CustomerAction,
	hero: Hero,
	icon_text: IconText,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	services_carousel: ServicesCarousel,
	text: Text,
	text_with_image: TextWithImage,
	user_profile: UserProfile,
	video: Video,
};
